### PR TITLE
non-functional changes

### PR DESCRIPTION
**Pull request by djzort**
tweaking pod and dist.ini

adding a Dockerfile to help people hack on this code quickly to help with #111

### CODE REVIEW

**Comment by whindsx** [comment]
For my case the docker build was failing on DBI missing and DBD::Oracle looking for InstantClient. I was able to fix it with the below changes:

```
diff --git a/maint/Dockerfile b/maint/Dockerfile
index f7e8c43..e63a89d 100644
--- a/maint/Dockerfile
+++ b/maint/Dockerfile
@@ -25,9 +25,10 @@ ENV ORACLE_USERID=kermit/foobar \
 COPY . /usr/src/DBD-Oracle
 RUN apt-get update && apt-get install -y libaio-dev && \
     apt-get install -y vim less net-tools && \
+    cpanm --verbose --notest DBI && \
+    /usr/src/DBD-Oracle/maint/travis-ci_scripts/02_install_oracle_instantclient.bash && \
     cpanm --verbose --notest --installdeps /usr/src/DBD-Oracle && \
     /usr/src/DBD-Oracle/maint/travis-ci_scripts/01_install_oracle_xe.bash && \
-    /usr/src/DBD-Oracle/maint/travis-ci_scripts/02_install_oracle_instantclient.bash && \
     sync && /etc/init.d/oracle-xe stop && apt-get clean
```

Otherwise it was fairly easy to get going, while having little Docker experience.

Docker version 18.09.1, build 4c52b90
Debian GNU/Linux 9.11 (stretch)

**Comment by djzort** [comment]
`cpanm --verbose --notest --installdeps /usr/src/DBD-Oracle` should take taken care of it?

**Comment by whindsx** [comment]
> `cpanm --verbose --notest --installdeps /usr/src/DBD-Oracle` should take taken care of it?

One would think.

Here's what I get:

```
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for mime-support (3.62) ...
cpanm (App::cpanminus) 1.7044 on perl 5.032000 built for x86_64-linux-gnu-thread-multi
Work directory is /root/.cpanm/work/1597328549.474
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Entering /usr/src/DBD-Oracle
Running Makefile.PL
--> Working on /usr/src/DBD-Oracle
Configuring /usr/src/DBD-Oracle ... Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/local/lib/perl5/site_perl/5.32.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/site_perl/5.32.0 /usr/local/lib/perl5/vendor_perl/5.32.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/vendor_perl/5.32.0 /usr/local/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /usr/local/lib/perl5/5.32.0 .) at Makefile.PL line 20.
BEGIN failed--compilation aborted at Makefile.PL line 20.
N/A
! Configuring /usr/src/DBD-Oracle failed. See /root/.cpanm/work/1597328549.474/build.log for details.
The command '/bin/sh -c apt-get update && apt-get install -y libaio-dev &&     apt-get install -y vim less net-tools &&     cpanm --verbose --notest --installdeps /usr/src/DBD-Oracle &&     /usr/src/DBD-Oracle/maint/travis-ci_scripts/01_install_oracle_xe.bash &&     /usr/src/DBD-Oracle/maint/travis-ci_scripts/02_install_oracle_instantclient.bash &&     sync && /etc/init.d/oracle-xe stop && apt-get clean' returned a non-zero code: 1
```
Docker version 19.03.12, build 48a66213fe
Debian GNU/Linux 9.12 (stretch)

Obviously it has something to do with `use DBI` being in Makefile.PL and also being a requirement.

**Comment by djzort** [comment]
@whindsx thats really strange as DBI is literally in the cpanfile... hmm

**Pull request merged**
