### PR TITLE
Clean ups on dist.ini and .travis.yml

### PR DESCRIPTION
**Pull request by djzort**
Just some small tidy ups.

It would be nice if we could make another minor release to CPAN after these

### CODE REVIEW

**Comment by mjegh** [comment]
@dzort - if you can find someone capable of building a new distribution I will happily upload it.

**Comment by djzort** [comment]
You should just be able to go:

dzil build
dzil release

Otherwise, please bump the versions and make a tag. I will roll a tarball for you.

**Comment by mjegh** [comment]
yep, this is exactly the problem. I cannot use dzil and to bump the version numbers I have to go through the files where the version goes and undo the dzil placeholders.

**Comment by djzort** [comment]
Can i help with dzil on your local machine?

**Comment by mjegh** [comment]
Sure. I've forgotten what the problem was so let me remind myself first. I'm on #dbi on irc.perl.org as mje.

**Pull request merged**
